  main[m
* [32mteam6/Items[m
  [31mremotes/origin/106-level-system[m
  [31mremotes/origin/140-plate-component[m
  [31mremotes/origin/22-making-customer-entity[m
  [31mremotes/origin/27-render-order-ticket-instance[m
  [31mremotes/origin/34-freezing-player[m
  [31mremotes/origin/39-spawning-controller-for-customer[m
  [31mremotes/origin/40-customer-movement-task[m
  [31mremotes/origin/58-dckt-sts[m
  [31mremotes/origin/61-22-branch[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/ImLeiSu-patch-1[m
  [31mremotes/origin/PlayerAnimation[m
  [31mremotes/origin/Station-Processing-Framework-#3[m
  [31mremotes/origin/Team2-Food-recipe[m
  [31mremotes/origin/bench-rework[m
  [31mremotes/origin/create-background-screen[m
  [31mremotes/origin/customer-creation[m
  [31mremotes/origin/customer-implementation[m
  [31mremotes/origin/detached[m
  [31mremotes/origin/detached2[m
  [31mremotes/origin/feature/stations[m
  [31mremotes/origin/gh-pages[m
  [31mremotes/origin/main[m
  [31mremotes/origin/order-docketImage-movement[m
  [31mremotes/origin/origin/team6[m
  [31mremotes/origin/quick-fixes[m
  [31mremotes/origin/revert-49-Team08[m
  [31mremotes/origin/team1/inventory[m
  [31mremotes/origin/team1/meal[m
  [31mremotes/origin/team3/#112_fire[m
  [31mremotes/origin/team3/Interaction-Key-Bindings[m
  [31mremotes/origin/team3/Keybinds-UI-#26[m
  [31mremotes/origin/team3/Player-Action-Interaction-#4[m
  [31mremotes/origin/team3/fire_extinguisher[m
  [31mremotes/origin/team3/fire_extinguisher_assets[m
  [31mremotes/origin/team3/fire_extinguisher_station[m
  [31mremotes/origin/team4-enlarge-docket[m
  [31mremotes/origin/team4-order-system[m
  [31mremotes/origin/team4/25-Pinned-Docket-Line[m
  [31mremotes/origin/team4/62-Docket-Data[m
  [31mremotes/origin/team4/order-system-bug-fixes[m
  [31mremotes/origin/team4/sprint2[m
  [31mremotes/origin/team6/Items[m
  [31mremotes/origin/team7-benches[m
  [31mremotes/origin/team7-map[m
  [31mremotes/origin/team8-s1[m
  [31mremotes/origin/team8-s1-aiden-1[m
  [31mremotes/origin/team8/team-branch[m
  [31mremotes/origin/team8/team-branch-aiden-01[m
  [31mremotes/origin/test-and-documentation[m
  [31mremotes/origin/uhoh-spaghettios[m
  [31mremotes/origin/uhoh-spaghettios-2-the-sequel[m
